project:
  type: book

book:
  title: "LangChain Notes"
  author: "Kittipos Sirivongrungson"
  date: "6/8/2024"
  repo-url: https://github.com/Lightbridge-KS/langchain-notes
  site-url: https://langchain-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: "Basic"
      chapters: 
        - "basic/quickstart.ipynb"
        - "basic/simple-llm.ipynb"
    - part: "LCEL"
      chapters: 
        - "LCEL/lcel-1.ipynb"
    - part: "RAG"
      chapters: 
        - "rag/vector-store-retriver.ipynb"
        - "rag/extraction-chain.ipynb"
    - part: "Tables Extract"
      chapters: 
        - "tables/qa-csv.ipynb"
    - part: "PDF"
      chapters: 
        - "pdf-ingest/pdf-qa-1.ipynb"
        - "pdf-ingest/pdf-qa-2.ipynb"
    - part: "How to"
      chapters: 
        - "basic/build-chatbot.ipynb"
        - "basic/build-rag-app-web.ipynb"
        - "telephone/telephone-bot.ipynb"


format:
  html:
    theme: zephyrs

execute:
  freeze: auto

