project:
  type: book

book:
  title: "LangChain Notes"
  author: "Kittipos Sirivongrungson"
  date: "6/8/2024"
  repo-url: https://github.com/Lightbridge-KS/langchain-notes
  site-url: https://langchain-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: "Basic"
      chapters: 
        - "basic/quickstart.ipynb"
        - "basic/simple-llm.ipynb"
        - "history/msg-history.ipynb"
    - part: "LCEL"
      chapters: 
        - "LCEL/lcel-1.ipynb"
        - "LCEL/lcel-2.ipynb"
        - "LCEL/lcel-deepdive.ipynb"
    - part: "PDF Loading"
      chapters: 
        - "pdf-load/pdf-load-simple.ipynb"
        - "pdf-load/pdf-load-unstructured.ipynb"
        - "pdf-load/pdf-load-pymu.ipynb"
    - part: "Parse"
      chapters:
        - "parse/html-to-md.ipynb"
    - part: "RAG"
      chapters: 
        - "rag/vector-store-retriver.ipynb"
        - "rag/extraction-chain.ipynb"
        - "ollama/ollama-rag.ipynb"
    - part: "Tables Extract"
      chapters: 
        - "tables/qa-csv.ipynb"
    - part: "PDF"
      chapters: 
        - "pdf-ingest/pdf-qa-1.ipynb"
        - "pdf-ingest/pdf-qa-2.ipynb"
    - part: "CSV"
      chapters: 
        - "CSV/csv_load.ipynb"
        - "CSV/telephone-csv.ipynb"
    - part: "Agent"
      chapters:
        - "agent/agent-basic.ipynb"
        - "agent/tool-calling.ipynb"
    - part: "LangChain for LLM App"
      chapters: 
        - "lc-app-dev/L1-Model_prompt_parser.ipynb"
        - "lc-app-dev/L2-Memory.ipynb"
        - "lc-app-dev/L3-Chains.ipynb"
    - part: "Local LLM"
      chapters: 
        - "local/lc-local-model.ipynb"
    - part: "How to"
      chapters: 
        - "basic/build-chatbot.ipynb"
        - "basic/build-rag-app-web.ipynb"
        - "telephone/telephone-bot.ipynb"


format:
  html:
    theme: zephyrs

execute:
  freeze: auto

